# Default values for liferay.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: liferay/portal
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: liferay.local
      paths: ["/"]
  tls: []

resources:
  requests:
    memory: "4096Mi"
    cpu: "2"
  limits:
    memory: "6144Mi"
    cpu: "4"

nodeSelector: {}

tolerations: []

affinity: {}

java:
  version: zulu11
  opts: -Xms4g -Xmx4g

files:
  mountPath: /mnt/liferay
deploy:
  mountPath: /opt/liferay/deploy
