# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mysql
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3306

ingress:
  enabled: false

resources:
  limits:
    memory: "512Mi"
    cpu: "0.5"

nodeSelector: {}

tolerations: []

affinity: {}

mountPath:
  data: /var/lib/mysql
