kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mysql.fullname" . }}-data-pvc
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ include "mysql.fullname" . }}-data-pv
