apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liferay.fullname" . }}
  labels:
    {{- include "liferay.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "liferay.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "liferay.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "liferay.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JAVA_VERSION
              value: {{ .Values.java.version }}
            - name: LIFERAY_JVM_OPTS
              value: {{ .Values.java.opts }}
            - name: LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE
              value: 0.0.0.0:11311
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: gogoshell
              containerPort: 11311
              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/c/portal/layout"
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 3
            successThreshold: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
